python finetune.py \
    --train_samples 8000 \
    --eval_samples 64 \
    --custom_mode sara \
    --lr 4e-3 \
    --lora_r 256 \
    --train_bs 4 \
    --eval_bs 4 \
    --custom_disable_identity \
    --accumulation_steps 4 \
    --model meta-llama/Llama-2-7b-hf \
    --quantize \
    --seed 42 \
    --eval_steps 20 \
    --logging_steps 1 \
    --target_modules no_head \
    --generate_samples \
    --metrics_enabled 0 \
    --lr_scheduler_type cosine \
    --task math \
    --dataset gsm10k \
    --init_type 1 \
    --d_init_type 100 \
    --epochs 1 \
    --dynamic_uv 1 \
    --shared_dim 11008 \
    --shared_uv 1 \
    --offline